file:
    path:     /
    defaults: { _controller: "UserBundle:file:index" }

file_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:file:show" }

file_new:
    path:     /new
    defaults: { _controller: "UserBundle:file:new" }

file_create:
    path:     /create
    defaults: { _controller: "UserBundle:file:create" }
    methods:  POST

file_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:file:edit" }

file_update:
    path:     /{id}/update
    defaults: { _controller: "UserBundle:file:update" }
    methods:  [POST, PUT]

file_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:file:delete" }
    methods:  [POST, DELETE]
