user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /usuario

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
login:
    pattern:   /login
    defaults:  { _controller: UserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

