producto:
    path:     /
    defaults: { _controller: "CartBundle:producto:index" }

producto_show:
    path:     /{id}/show
    defaults: { _controller: "CartBundle:producto:show" }

producto_new:
    path:     /new
    defaults: { _controller: "CartBundle:producto:new" }

producto_create:
    path:     /create
    defaults: { _controller: "CartBundle:producto:create" }
    methods:  POST

producto_edit:
    path:     /{id}/edit
    defaults: { _controller: "CartBundle:producto:edit" }

producto_update:
    path:     /{id}/update
    defaults: { _controller: "CartBundle:producto:update" }
    methods:  [POST, PUT]

producto_delete:
    path:     /{id}/delete
    defaults: { _controller: "CartBundle:producto:delete" }
    methods:  [POST, DELETE]
